#!/usr/bin/env php

<?php

require_once 'vendor/autoload.php';

$birthDate = '1972-10-28';
$days = new \Evgeniyholon\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo "$birthDate : $totalDays days\n\n";
